LineLength:
  Description: 'Limit lines to 120 characters.'
  Enabled: true
  Max: 120

SpaceInsideHashLiteralBraces:
  Description: "Use spaces inside hash literal braces - or don't."
  Enabled: false

ConstantName:
  Enabled: false

AndOr:
  Enabled: false
